### ISSUE TITLE
Please stop distributing prebuilt VyOS images with our trademarks and artwork intact

### ISSUE THREAD

**Issue by dmbaturin** [francisschmaltz/francis-vyos-lts#1]
Dear Francis,

We’ve noticed that you build VyOS LTS release images and make them available for everyone to download, with VyOS name and artwork intact. We understand that your work is well-intentioned and you are driven by a desire to bring VyOS to more people.

We have nothing against people building and using their own VyOS LTS images, which is why we keep the build toolchain public and document the build procedures. However, distributing images is a different matter. Since the images are identifiable as VyOS, if someone uploads an incorrectly-built or, worse, backdoored image, the public will hold us responsible for the incident, not you.

Since our ability to stay in business and maintain the project rests on our reputation with customers, we cannot risk our reputation by allowing unauthorized third parties to distribute images with our branding. We are not alone in that: RedHat has the same policy for RHEL, and Mozilla requires a written permission to use the Firefox name for third-party builds.

Besides, we already offer plenty of opportunities to get VyOS LTS releases at a very low or no cost, by making them available to project contributors and for small monthly donations. By giving people prebuilt images you give them a short-term advantage, but undermine the long-term project sustainability.

Please either stop distributing pre-built images or replace the VyOS name and the artwork that features the VyOS name or logo with your own.

We hope you understand our position and will comply with this request voluntarily. If not, we reserve the right to enforce our trademarks and artwork copyright.

Sincerely,
Daniil,
VyOS project founder and maintainer

**Comment by francisschmaltz** [comment]
I've deleted the built binaries from this repo. Thanks for making the LTS build to paid patreon members
